version: "3.3"
   
services:
  db:
    image: postgres
    env_file:
      - wishl.env
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - wishl.env
    ports:
      - "8000:8000"
    depends_on:
      - db
