# Generated by Django 3.1.1 on 2020-09-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishl_api', '0002_auto_20200928_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='path',
        ),
    ]
