# Generated by Django 3.1.1 on 2020-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishl_api', '0006_auto_20200928_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybox',
            name='goal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
