# Generated by Django 3.1.1 on 2020-09-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishl_api', '0007_auto_20200928_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='tags',
        ),
        migrations.AddField(
            model_name='wish',
            name='tags',
            field=models.ManyToManyField(to='wishl_api.Tag'),
        ),
    ]
