# Generated by Django 3.1.1 on 2020-10-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishl_api', '0010_wish_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='name',
            new_name='title',
        ),
    ]
