# Generated by Django 3.1.1 on 2020-10-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishl_api', '0011_auto_20201001_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneybox',
            name='name',
        ),
    ]
